# Generated by Django 4.1 on 2022-09-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, unique=True)),
                ('fromdate', models.DateField(unique=True)),
                ('todate', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('as_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('expenseType', models.CharField(choices=[('indirectExpense', 'indirect Expense'), ('directExpense', 'direct Expense')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('opening_balance', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrpParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('opening_balance', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrpService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=50)),
                ('service_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('sale_price', models.CharField(max_length=100)),
                ('sale_price_type', models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], max_length=50)),
                ('tax_rate', models.CharField(choices=[('0.25', 'GST@0.25%'), ('0.25', 'IGST@0.25%'), ('3.0', 'GST@3%'), ('3.0', 'IGST@3%'), ('5.0', 'GST@5%'), ('5.0', 'IGST@5%'), ('12.0', 'GST@12%'), ('18.0', 'GST@18%'), ('18.0', 'IGST@18%'), ('28.0', 'GST@28%'), ('28.0', 'IGST@28%'), ('12.0', 'IGST@12%'), ('0.0', 'IGST@0%')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.IntegerField()),
                ('product_code', models.CharField(max_length=100)),
                ('sale_price', models.CharField(max_length=100)),
                ('sale_price_type', models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], max_length=50)),
                ('purchase_price', models.CharField(max_length=100)),
                ('purchase_price_type', models.CharField(choices=[('withTax', 'with Tax'), ('withoutTax', 'without Tax')], max_length=50)),
                ('tax_rate', models.CharField(choices=[('0.25', 'GST@0.25%'), ('0.25', 'IGST@0.25%'), ('3.0', 'GST@3%'), ('3.0', 'IGST@3%'), ('5.0', 'GST@5%'), ('5.0', 'IGST@5%'), ('12.0', 'GST@12%'), ('18.0', 'GST@18%'), ('18.0', 'IGST@18%'), ('28.0', 'GST@28%'), ('28.0', 'IGST@28%'), ('12.0', 'IGST@12%'), ('0.0', 'IGST@0%')], max_length=20)),
                ('opening_stock', models.CharField(max_length=100)),
                ('price_per_unit', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('minimum_stock_quantity', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(unique=True)),
                ('on_account_of', models.CharField(max_length=100)),
                ('accounting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.accounting_year')),
            ],
        ),
    ]
