# Generated by Django 4.1 on 2022-09-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='photograph_doc',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/photograph/'),
        ),
    ]
