# Generated by Django 4.1 on 2022-09-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('workdate', models.DateTimeField(auto_now_add=True)),
                ('work_detail', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.emp')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.party')),
            ],
        ),
    ]
