# Generated by Django 4.1 on 2022-09-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('challan_no', models.IntegerField()),
                ('subtotal_amount', models.IntegerField()),
                ('final_amount', models.IntegerField()),
                ('state_of_supply', models.CharField(choices=[('SELECT', 'Select'), ('ANDHRA PRADESH', 'Andhra Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('GOA', 'Goa'), ('GUJRAT', 'Gujrat'), ('HARYANA', 'Haryana'), ('HIMACHAL PRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYA PRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamilnadu'), ('TELENGANA', 'Telengana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTAR PRADESH', 'Uttar pradesh'), ('WEST BENGAL', 'West bengal'), ('ANADAMAN & NICOBAR ISLANDS', 'Andaman & Nicobar Islands'), ('DADRA and NAGAR HAVELI and DAMAN & DIU', 'Dadra & Nagar Haveli and Daman & Diu'), ('JAMMU & KASHMIR', 'Jammu & Kashmir'), ('LAKSHADWEEP', 'Lakshadweep'), ('THE GOVERNMENT of NCT of DELHI', 'The Government of NCT of Delhi'), ('LADAKH', 'Ladakh'), ('PUDUCHERRY', 'Puducherry')], default='SELECT', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.emp')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.party')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.accounting_year')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Billings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subtotal_amount', models.IntegerField()),
                ('final_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=30)),
                ('state_of_supply', models.CharField(choices=[('SELECT', 'Select'), ('ANDHRA PRADESH', 'Andhra Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('GOA', 'Goa'), ('GUJRAT', 'Gujrat'), ('HARYANA', 'Haryana'), ('HIMACHAL PRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYA PRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMILNADU', 'Tamilnadu'), ('TELENGANA', 'Telengana'), ('TRIPURA', 'Tripura'), ('UTTARAKHAND', 'Uttarakhand'), ('UTTAR PRADESH', 'Uttar pradesh'), ('WEST BENGAL', 'West bengal'), ('ANADAMAN & NICOBAR ISLANDS', 'Andaman & Nicobar Islands'), ('DADRA and NAGAR HAVELI and DAMAN & DIU', 'Dadra & Nagar Haveli and Daman & Diu'), ('JAMMU & KASHMIR', 'Jammu & Kashmir'), ('LAKSHADWEEP', 'Lakshadweep'), ('THE GOVERNMENT of NCT of DELHI', 'The Government of NCT of Delhi'), ('LADAKH', 'Ladakh'), ('PUDUCHERRY', 'Puducherry')], default='SELECT', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.party')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.accounting_year')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Sale_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_no', models.IntegerField()),
                ('total_sale', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('emp_party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.party')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.accounting_year')),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Add_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product')),
                ('emp_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.service')),
            ],
        ),
    ]
